const api_version = "api/v1";
const ip = "/cors";

export const APIS = {
  // 知识库部分
  get_repository: `${ip}/${api_version}/repository`,
  get_note: `${ip}/${api_version}/note/repository`,
  get_full_open_note: `${ip}/${api_version}/note/open`,
  create_repository: `${ip}/${api_version}/repository`,
  create_note:`${ip}/${api_version}/note`,
  update_note:`${ip}/${api_version}/note`,
  edit_all_privilege:`${ip}/${api_version}/notePrivilege/editAll`,
  edit_part_privilege:`${ip}/${api_version}/notePrivilege/editUserList`,
  get_search_users:`${ip}/${api_version}/userList/search`,
  get_user_privilege_of_note:`${ip}/${api_version}/notePrivilege`,
  get_share_room_note_list:`${ip}/${api_version}/notePrivilege/shareRoom`,
  get_repository_of_note:`${ip}/${api_version}/notePrivilege/shareRoom`,
  insert_recent_file:`${ip}/${api_version}/recentFile`,
  update_recent_file:`${ip}/${api_version}/recentFile/updateOrInsert`,
  get_recent_file_list:`${ip}/${api_version}/note/recent`,
  get_search_question:`${ip}/${api_version}/note/searchQuestion`,
  add_question:`${ip}/${api_version}/ask`,
  get_all_ask:`${ip}/${api_version}/ask/allAsk`,
  get_all_answer_of_question:`${ip}/${api_version}/answer`,
  get_ask_by_note_id:`${ip}/${api_version}/ask/getAsk`,
  post_answer:`${ip}/${api_version}/answer`,
  add_answer_likes:`${ip}/${api_version}/answer/addLikes`,
  sub_answer_likes:`${ip}/${api_version}/answer/subLikes`,
  get_likes_num:`${ip}/${api_version}/answer/likeNum`,
  post_share_message:`${ip}/${api_version}/message/postShareMessage`,
  get_ocr_result:`${ip}/${api_version}/ocr`,
  get_message_list:`${ip}/${api_version}/message/chatList`,
  get_unread_message_list:`${ip}/${api_version}/message/unreadList`,


  load_lessons: `${ip}/${api_version}/study/user`,
  get_comments: `${ip}/${api_version}/comment/section`,
  get_lesson_detail: `${ip}/${api_version}/study/lesson`,
  get_video: `${ip}/${api_version}/video`,
  login_by_account: `${ip}/${api_version}/users/login/account`,
  send_email_code: `${ip}/${api_version}/users/login/email/code`,
  verify_email_code: `${ip}/${api_version}/users/login/email/verify`,
  check_account: `${ip}/${api_version}/users/check/account`,
  check_email: `${ip}/${api_version}/users/check/email`,
  register: `${ip}/${api_version}/users/register`,
  get_video_chunck: `${ip}/${api_version}/video/chunk`,
  video_jump: `${ip}/${api_version}/video/jump`,
  stream_url: `${ip}/${api_version}/video/streaming`,
  update_checkpoint: `${ip}/${api_version}/video/checkpoint`,
  get_user: `${ip}/${api_version}/userList`,
  star_lesson: `${ip}/${api_version}/study/lesson/star`,
  record_study_min: `${ip}/${api_version}/video/record`,
  get_study_time: `${ip}/${api_version}/video/time/user`,
  add_new_comment: `${ip}/${api_version}/comment/new`,
  judge_is_teacher: `${ip}/${api_version}/users/teacher/exists`,
  get_teacher_info: `${ip}/${api_version}/teacher`,

  apply_live: `${ip}/${api_version}/live/uuid/user`,
  load_live_info: `${ip}/${api_version}/live`,

  check_file_md5: `${ip}/${api_version}/file`,

  upload_file: `${ip}/${api_version}/file/chunk`,
  upload_file_success: `${ip}/${api_version}/file`,
  get_browse_lesson_info:`${ip}/${api_version}/study/browse/lessons`,
  get_browse_live_info:`${ip}/${api_version}/live/allLive`,
};
